import type { Metadata } from 'next';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from '../providers/SessionProvider';
import Navbar from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body>
        {/* <SessionProvider session={session}> */}
          <main>{children}</main>
          <Navbar />
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
