import { ListProvider } from '@/providers/ListContext';
import SessionProvider from '@/providers/SessionProvider';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';

import Navbar from '@/components/Navbar/Navbar';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();
	return (
		<html lang="en">
			<body>
				<SessionProvider session={session}>
					<ListProvider>
						<main className="px-5 mb-28">{children}</main>
					</ListProvider>
					<Navbar />
				</SessionProvider>
			</body>
		</html>
	);
}
